version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-2mamd44ylve3"
s3_prefix = "sam-app"
region = "us-east-1"
profile = "joaoco"
capabilities = "CAPABILITY_IAM"
