AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  poc

  Sample SAM Template for poc

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5

Resources:
  AppFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.8
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DynamoDBTable
      # table name as environment variable
      Environment:
        Variables:
          TABLE_NAME: !Ref DynamoDBTable
      Events:
        App:
          Type: Api
          Properties:
            Path: /app
            Method: post
      # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/automating-updates-to-serverless-apps.html
      AutoPublishAlias: live
      DeploymentPreference:
        Type: AllAtOnce

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    # in case CloudFormation script is deleted, table is not deleted
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: app
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/app/"
